# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptLocation: inlineScript
    arguments: '$(Build.SourcesDirectory) $(CustomerUID) $(ShareName) $(ConnectionString) $(ProjectUID) $(ProjectVersion) $(dirName)'
    inlineScript: |
     az account set --subscription 32f3494c-80c6-4f55-971a-9c62509839a5
     az aks get-credentials --resource-group rgfrontfactoryprod --name aksfrontfactoryprod
     mkdir -p $1/temp
     mkdir -p $1/temp2
     az storage file download --path "$2/$5/$6/$7.zip" --share-name "$3" --account-name asafrontfactoryprod --dest "$1/temp" --connection-string "$4"
     ls $1/temp
     
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.SourcesDirectory)/temp/$(dirName).zip'
    destinationFolder: '$(Build.SourcesDirectory)/temp2/'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
  
- task: Docker@2
  inputs:
    containerRegistry: 'acrff'
    repository: 'customer/$(CustomerUID)/$(ProjectUID)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/temp2/dockerfile'
    tags: $(ProjectVersion)

- task: file-creator@6
  inputs:
    filepath: 'main.tf'
    filecontent: |
      terraform {
        required_providers {
          azurerm = {
            source  = "hashicorp/azurerm"
            version = "=2.52.0"
          }
        }
        backend "azurerm" {
          resource_group_name   = "rgfrontfactoryprod"
          storage_account_name  = "asafrontfactoryprod"
          container_name        = "terraform"
          key                   = "terraform.tfstate"
        }
      }
      provider "kubernetes" {
        config_path    = "~/.kube/config"
        config_context = "aksfrontfactoryprod"
      }
      
      resource "kubernetes_namespace" "customer-namespace-$(CustomerUID)" {
        metadata {
          name = "customer-namespace-$(CustomerUID)"
        }
      }

      resource "kubernetes_service" "customer-service-$(ProjectUID)-$(CustomerUID)" {
        metadata {
          name = "customer-service-$(ProjectUID)-$(CustomerUID)"
      	  namespace = "customer-namespace-$(CustomerUID)"
        }
        spec {
          selector = {
            app = kubernetes_pod.customer-pod-$(ProjectUID)-$(CustomerUID).metadata.0.labels.app
          }
          session_affinity = "ClientIP"
          port {
            port        = 80
            target_port = 80
          }
      
          type = "LoadBalancer"
        }
      }
      
      resource "kubernetes_pod" "customer-pod-$(ProjectUID)-$(CustomerUID)" {
        metadata {
          name = "customer-pod-$(ProjectUID)-$(CustomerUID)"
      	  namespace = "customer-namespace-$(CustomerUID)"
          labels = {
            app = "customer-pod-$(ProjectUID)-$(CustomerUID)"
          }
        }
      
        spec {
          container {
            image = "acrff.azurecr.io/customer/$(CustomerUID)/$(ProjectUID):$(ProjectVersion)"
            name  = "customer-pod-$(ProjectUID)-$(CustomerUID)"
          }
        }
      }
    fileoverwrite: true

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(azureResourceManagerConnection)
    backendAzureRmResourceGroupName: 'rgfrontfactoryprod'
    backendAzureRmStorageAccountName: 'asafrontfactoryprod'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform workspace new $1
      terraform workspace select $1
      terraform validate
      terraform apply -input=false -auto-approve
    arguments: '$(CustomerUID)'
