# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: file-creator@6
  inputs:
    filepath: 'main.tf'
    filecontent: |
      terraform {
        required_providers {
          azurerm = {
            source  = "hashicorp/azurerm"
            version = "=2.52.0"
          }
        }
        backend "azurerm" {
          resource_group_name   = "rgfrontfactoryprodv2"
          storage_account_name  = "asafrontfactoryprodv2"
          container_name        = "terraform"
          key                   = "terraform.tfstate"
        }
      }
      provider "kubernetes" {
        config_path    = "~/.kube/config"
        config_context = "aksfrontfactoryprodv2"
      }
    fileoverwrite: true

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(azureResourceManagerConnection)
    backendAzureRmResourceGroupName: 'rgfrontfactoryprodv2'
    backendAzureRmStorageAccountName: 'asafrontfactoryprodv2'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription e2270597-5099-424b-9597-6c5963dd2d81
      az aks get-credentials --resource-group rgfrontfactoryprodv2 --name aksfrontfactoryprodv2
      terraform workspace select $2
      terraform apply -input=false -auto-approve
    arguments: '$(ProjectUID) $(CustomerUID)'
    failOnStandardError: false
