# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptLocation: inlineScript
    arguments: '$(Build.SourcesDirectory) $(CustomerUID) $(ShareName) $(ConnectionString) $(storageAccountKey)'
    inlineScript: |
     mkdir -p $1/temp
     az storage file download --path "projects/$2/$2.zip" --share-name "$3" --account-name storageff --dest "$1/temp" --connection-string "$4"
     apt install unzip
     unzip $1/temp/$2.zip
     ls $1/temp

- task: Docker@2
  inputs:
    containerRegistry: 'frontfactory docker'
    repository: 'customers'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/temp/$(CustomerUID)/dockerfile'




