# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform workspace select $2
      terraform destroy --target kubernetes_service.customer-service-$1-$2
      terraform destroy --target kubernetes_pod.customer-pod-$1-$2
    arguments: '$(ProjectUID) $(CustomerUID)'
